### ISSUE TITLE
Translation of GRA Foreword

### ISSUE THREAD

**Issue by fxru** [sanskrit-lexicon/GRA#2]
Hi, I wanted to send a pull request for my translation of the Foreword, but I don’t have the permissions to do that, so I’ll attach my translation here to this issue.

The German text is extremely densely written, very archaic (especially in its linguistic terminology), and in a few places I have indicated in brackets `[FR ....]` where I am unsure about the meaning of a word or phrase. I have tried to keep the text in idiomatic English, but the tediously nested and long construction of Grassmann’s German, don’t make it easy. I hope my translation is somewhat more coherent than Google Translate’s version. 

[GRA_foreword_engl.txt](https://github.com/sanskrit-lexicon/GRA/files/2479905/GRA_foreword_engl.txt)

**Comment by gasyoun** [comment]
>  somewhat more coherent than Google Translate’s version.

Amazing work. Are you aware of the new edition of Grassmann’s Dictionary that is still in print in Germany?

**Comment by fxru** [comment]
If you mean the revised and complemented edition by Maria Kozianka from the 90s, then yes, we have it here in Cologne in the department.

As for my translation of the foreward: It’s not a particularly good translation, but Jim said it would help, so I did my best. (It’s really tedious German.), I hope it helps. I just fixed some typos in the my translation, probably still too many in it, though:
[GRA_foreword_engl-fixed-typos.txt](https://github.com/sanskrit-lexicon/GRA/files/2485071/GRA_foreword_engl-fixed-typos.txt)

**Comment by funderburkjim** [comment]
Thanks, @fxru !

I've uploaded the two files to the repository.

@marcis  --  Can you do the needed so Felix has permissions?

I think the way to use this improved translation is to add it to the [front matter for Grassman](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/grapref.html).

Do others agree?

**Comment by gasyoun** [comment]
> If you mean the revised and complemented edition by Maria Kozianka from the 90s, then yes, we have it here in Cologne in the department.

No, I mean the newer one.

> Do others agree?

Sure.

> Can you do the needed so Felix has permissions?

No easy way. Are you back for more @fxru or is it just a one-time commitment?

**Comment by fxru** [comment]
I’m happy to do more, I just can’t put that much time into it, so I might be slow. I could do smaller things related to XML or German, ideally things that are not too time sensitive.

**Comment by funderburkjim** [comment]
@fxru 

Hi, Felix.  I've finally got a preliminary embedding of your translation into a new version of the documentation subsystem.  This subsystem is in the [csldoc](https://github.com/sanskrit-lexicon/csldoc) repository.

Here is the [source page](https://github.com/sanskrit-lexicon/csldoc/blob/master/source/dictionaries/prefaces/grapref/grapref06.rst) containing the translation.  
 I started with  `GRA_foreword_engl-fixed-typos.txt`

For technical reasons (ease in tracking changes via git), I made the lines shorter, breaking at word
boundaries so lines would be 72 characters or less in length.

I also proof read the file, and made a few very minor changes intended to correct typos.  You can review these changes at this [history url](https://github.com/sanskrit-lexicon/csldoc/commit/8d8b863ea48a4ba3e51e068623284895963e6f34#diff-eb557a3efc811652310d36785fea13ab)

One place that confused me was the word 'list' at line 163.  I changed to 'listed' but am not sure of the sense.

Also, I added a reference to you as the translator at the end of text -- glad to adjust the wording here
to your preference.

Finally, I made a change to the table of references at the end.   By adding the initial vertical bar, these
lines appear separately, rather than being gathered into one line.   This is a feature of the 'restructured text' specification.  The ending html is generated by the Sphinx document generator, whose syntax is based on restructured text.

As a general comment, I like the translation a lot.  For an English speaker like me,  the translation is a great help in understanding Grassman's approach, although some of the finer points regarding his organization of items are too subtle for me currently.

**I think you should double check the changes I made.**

Then, I'll get some space allocated at Cologne to install this repository, and make it the current version of the documentation.

**Comment by fxru** [comment]
I looked at commit 8d8b863 and all corrections are extremely helpful. 

line 163 “list” should have been “lost” (“had not yet lost their final consonant”).

Thanks :)

**Comment by gasyoun** [comment]
@fxru did you attain what you wanted to?

**Comment by drdhaval2785** [comment]
The English translation is in the csl-doc repository i.e. documentation. Also the correction regarding list->lost was made as @fxru suggested. Closing this issue.
