### ISSUE TITLE
Error in AV digitisation provided by Marcis

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/GRA#30]
@gasyoun 

Compare the Devanagari text at your collection

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/1c85207a-0d73-4a00-871c-37916c5744aa)

against the one at Vedicheritage.gov.in

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/39dcbba7-ef86-414e-86ed-78333d637644)

However, your Roman transliteration appears correct here.

Guess, these kind of errors would be present at more places too!!
[Another good proofing of the texts might be thought of; or a quick comparison between the Devanagari text and the Roman text, with a "logic" similar to the one proposed by @Yuzki recently at a "PWG RV issue" could bring out such errors. ]

**Comment by Andhrabharati** [comment]
I was referring to the text portion alone here, not the accents!

**Comment by funderburkjim** [comment]
Interestingly, when I display 11.001.05 at this link,
https://sanskrit-lexicon.github.io/avlinks/avhymns/av11.001.html,
the display shows 
<img width="443" alt="image" src="https://github.com/sanskrit-lexicon/GRA/assets/6393033/22c2c346-ff6b-4adf-91d4-3c8edf12a0a8">

The css for devanagari shows
```
/* Vedic devanagari */
p.sa {
 color: #8b0000;
 background: white;
 font-size: 16pt;
font-family: "Sanskrit 2003";
 padding-right: 40px;
}
```
But there is no web-font loaded for Sanskrit 2003.

The actual font used in my system is Nirmala.

This could be changed by adding a font-face directive in the css,
analogous to
```
@font-face { 
  src: url(../../web/fonts/siddhanta1.ttf); /*change siddhanta1 08-18-2021 */
  
 font-family: siddhanta_deva;
}
.sdata_siddhanta {
 color:teal;
 font-size:larger;
 font-weight: normal; /* 07-14-2018*/
 font-family: siddhanta_deva;
}
```
with  appropriate path for src:url

**Comment by funderburkjim** [comment]
@gasyoun   The rvlinks repository needs to be similarly examined and corrected if needed.
  Will you take care of this?

**Comment by Andhrabharati** [comment]
I have posted an issue on RV digitisation also sometime back in this GRA repo itself..

No response yet from @gasyoun on it!!

**Comment by Yuzki** [comment]
The incorrect long vowel "r" in Devanagari appears to be due to the following codepoints:
U+0924 त DEVANAGARI LETTER TA
U+0943 ृ DEVANAGARI VOWEL SIGN VOCALIC R
U+0304 ̄ COMBINING MACRON

Without knowing the original format or transliteration of the electronic text, it is difficult to determine the exact cause of the error. It is possible that there is an error in the conversion of long vowels or that the original text's macron was not processed correctly (if the original electronic text contained macrons).

By the way, RV seems to be unaffected by this issue.

![スクリーンショット 2023-06-20 111835](https://github.com/sanskrit-lexicon/GRA/assets/42864533/8e349474-6e71-4207-a049-f60c66d11971)
